services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: auction
    ports:
      - "5432:5432"
    volumes:
      - pdgdata:/var/lib/postgresql/data
volumes: 
    pdgdata:
  